---
title: "visualization" 
author: "Maxwel Coura Oliveira"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```


```{r}
population <- readxl::read_excel("2020_Marestail_Data.xlsx", sheet = "Populations") 
```

```{r}
population1 <- population %>% 
  janitor::clean_names() %>% 
  mutate(pop = row_number()) %>% 
  dplyr::select(id, pop, county, lat, long, crop, date_collected, location) %>% 
  rename(pop_id = id) %>% 
  mutate(pop_id = str_replace(pop_id, "M", "H"))
```



```{r}
data <- readxl::read_excel("2020_Marestail_Data.xlsx", sheet = "Data")
```

```{r}
data1 <- data %>% 
  janitor::clean_names() %>% 
  pivot_longer(cols = x7dat_control_percent:x21dat_control_percent,
               names_to = "dat", values_to = "weed_control") %>% 
  rename(biomass_g = biomass_21dat_g) %>% 
  mutate(dat = fct_recode(dat,
    "7" = "x7dat_control_percent",
    "14" = "x14dat_control_percent",
    "21" = "x21dat_control_percent"
  )) %>% 
  mutate(weed_control = weed_control,
         weed_control = case_when(
    weed_control == 100   ~ 99.9,
    weed_control == 0   ~ 0.001,
    TRUE                ~ weed_control)) %>% 
  mutate(biomass_g = if_else(is.na(biomass_g), 0, biomass_g)) 
```


```{r}
data2 <- data1 %>% 
  left_join(population1, by = "pop") %>% 
  mutate(county = str_replace(county, "Washjington", "Washington")) %>% 
  mutate(county = str_replace(county, "Washington", "Jefferson"),
         county = str_replace(county, "Columbia", "Dane"))
```


```{r}
data3 <- data2 %>% 
  filter(trt != "Check") %>% 
  mutate(pop_id = fct_relevel(pop_id, levels = "H1", "H2", "H3", "H4", "H5", "H6", 
                              "H7", "H8", "H9", "H10",
                              "H11", "H12", "H13", "H14", "H15", "H16", 
                              "H17", "H18", "H19", "H20",
                              "H21", "H22", "H23")) %>% 
  mutate(herbicide = fct_recode(trt,
                                "2,4-D (#4)" = "2,4-D",
                                "1x glyphosate (#9)" = "1x Gly",
                                "3x glyphosate (#9)" = "3x Gly",
                                "mesotrione (#27)" = "Mesot",
                                "dicamba (#4)" = "Dicam",
                                "glufosinate (#10)" = "Gluf",
                                "atrazine (#5)" = "Atraz",
                                "imazethapyr (#2)" = "Imaz",
                                "paraquat (#22)" = "Paraq",
                                "saflufenacil (#14)" = "Saflu"),
         herbicide = fct_relevel(herbicide,
                                 levels = c("mesotrione (#27)", "paraquat (#22)", "saflufenacil (#14)",
                                            "glufosinate (#10)", "3x glyphosate (#9)", "1x glyphosate (#9)",
                                            "atrazine (#5)", "dicamba (#4)", "2,4-D (#4)", "imazethapyr (#2)")))
```

```{r message = FALSE, warning=FALSE}
library(extrafont)
library(ggtext)
#extrafont::loadfonts()

font_family <- 'Helvetica'
title_family <- "Arial Black"
legend_family <- "Comic Sans MS"
subtitle_family = "Arial"
background <- "#1D1D1D"
text_colour <- "white"
axis_colour <- "white"
plot_colour <- "#F5F5DC"

theme_style <- theme(axis.text.x = element_text(angle = 45, hjust = 1, 
                                                size = 12, color = "black",
                                                family = legend_family),
        axis.text.y = element_text(size = 12, family = font_family, color = "black"),
        plot.title.position = "plot",
        plot.title = element_markdown(vjust = 2, size = 20, 
                                  family = title_family, margin = margin(2,1,1,1)),
        legend.text = element_text(family = legend_family),
        legend.title = element_text(family = title_family, size =12, face = "bold"),
        plot.subtitle = element_markdown(vjust = 2, size = 12, family = subtitle_family),
        plot.caption = element_text(size = 9, family = subtitle_family, hjust = 0),
        axis.ticks.x = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = plot_colour),
        plot.background = element_rect(fill = plot_colour),
        panel.border = element_blank()) 

theme_set(theme_bw() + theme_style)
```


```{r}
fig1 <- data3 %>% 
  filter(dat == "21") %>% 
  ggplot(aes(x = herbicide, y = pop_id, fill = weed_control)) +
  geom_tile(color = NA) +
  coord_flip() +
  expand_limits(x = 0, y = 0) +
  scale_color_brewer(palette = "Paired") +
  scale_fill_gradient(name = "% weed control", low = "red", high = "limegreen",
                       limits = c(0, 100), breaks=c(0, 25, 50, 75, 100),
                       labels= c("0 %", "25%", "50", "75%", "100%")) +
  geom_point(aes(x = 0.2, y = pop_id, color = county), pch = 15, size = 6) +
  labs(title = "<b style='color:darkgreen;'>Horseweed</b> accessions response to herbicides", 
       subtitle = "This figure shows the level of <b style='color:darkgreen;'>horseweed</b> control with 9 herbicides from 8 sites of action (SOA) 21 DAT. <br>Imazethapyr (SOA Group #2) and glyphosate (#9) were not effective in most <b style='color:darkgreen;'>horseweed</b> accessions. <br>Group #4 (2,4-D and dicamba) and mesotrione (#27) presented lower efficacy when compared <br>to atrazine (#5), glufosinate (#10), saflufenacil (#14) and paraquat (#22).",
       caption = "Visualization: @maxwelco | Data: WiscWeeds",
       x = "", y = "", color = "County") +
  ggsave("status.png", width = 9, height = 6, dpi = 600)
```



## Maps --------------------------------


```{r}
library(maps)
library(ggthemes)
library(ggrepel)
```

```{r}
states = map_data("state") 
df <- filter(states, region =="wisconsin")
```

```{r}
counties <- map_data("county")
county <- filter(counties, region %in% c("illinois", "wisconsin")) %>% 
  mutate(subregion = str_to_title(subregion),
         subregion = str_replace(subregion, "Mchenry", "McHenry"))
```

```{r}
county %>% 
  filter(subregion == "Washington")
```


```{r}
map_pop <- data3 %>% 
  distinct(county) %>% 
  dplyr::select(county) %>% 
  mutate(harvest = "Yes") %>% 
  rename(subregion = county) %>% 
  mutate(subregion = str_replace(subregion, "Washington", "Jefferson"),
         subregion = str_replace(subregion, "Columbia", "Dane"))
```

```{r}
data4 <- county %>% 
 left_join(map_pop, by = "subregion")
```

```{r}
id_pop <- data3 %>% 
  distinct(long, lat, county, pop_id) %>% 
  mutate(subregion = str_replace(county, "Washington", "Jefferson"),
         subregion = str_replace(county, "Columbia", "Dane"))
```


```{r message = FALSE, warning=FALSE}
library(extrafont)
library(ggtext)
#extrafont::loadfonts()

font_family <- 'Helvetica'
title_family <- "Arial Black"
legend_family <- "Comic Sans MS"
subtitle_family = "Arial"
background <- "#1D1D1D"
text_colour <- "white"
axis_colour <- "white"
plot_colour <- "#F5F5DC"

theme_style <- theme(
        plot.title.position = "plot",
        plot.subtitle = element_markdown(vjust = 2, size = 12, family = subtitle_family),
        plot.caption = element_text(size = 9, family = subtitle_family, hjust = 0),
        plot.title = element_markdown(vjust = 2, size = 20, 
                                  family = title_family, margin = margin(2,1,1,1)),
        legend.text = element_text(family = legend_family),
        legend.title = element_text(family = title_family, size =12, face = "bold"),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = plot_colour),
        panel.border = element_blank()) 

theme_set(theme_void() + theme_style)
```



```{r}
fig2 <- ggplot(data4, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(color = "black", fill = "grey90") +
  geom_polygon(data = data4 %>% 
                 filter(!is.na(harvest)), aes(x = long, y = lat,
                                             fill = subregion, 
                                             group = group), 
               color = "#282728") +
  ylim(41.5, 47) +
  xlim(-93, -86.5) +
  labs(fill = "County",
       title = "<b style='color:darkgreen;'>Horseweed</b> accessions identification",
       subtitle = "18 <b style='color:darkgreen;'>horseweed</b> accessions were harvested in <b style='color:#c5050c;'>Wisconsin</b> and 3 accessions in <b style='color:#13294B;'>Illinois</b>",
       caption = "Visualization: @maxwelco | Data: WiscWeeds") +
  geom_point(data = id_pop, aes(x = long, y = lat, group = pop_id)) +
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +
  geom_segment(aes(x = -91.6, y = 42.5, xend = -87.3, yend = 42.5),
               color = "black", size = 1.5) +
  annotate("text", x = -92.4, y = 42.75, label = "Wisconsin", size = 5,
           family = title_family, color = "#c5050c") +
  geom_segment(aes(x = -91.6, y = 42.5, xend = -91.6, yend = 43),
              arrow = arrow(length = unit(0.3, "cm")),
               color = "#c5050c", size =2) +
  annotate("text", x = -86.7, y = 42.25, label = "Illinois", size = 5,
           family = title_family, color = "#13294B") +
    geom_segment(aes(x = -87.3, y = 42.5, xend = -87.3, yend = 42),
              arrow = arrow(length = unit(0.3, "cm")),
               color = "#13294B", size = 2) +
  geom_label_repel(data = id_pop, aes(label = pop_id, group = 1, fill = subregion),
                  family = legend_family,
                  max.overlaps = 100,
                  box.padding   = 0.5, 
                  point.padding = 0.2,
                  segment.color = 'grey50', 
                  size = 3,
                  seed = TRUE,
                  show.legend = FALSE) +
#  coord_map() +


  
  ggsave("map.png", width = 8, height = 7, dpi = 300)
```



